### ISSUE TITLE
Drush Launcher use command isn't working as expected

### ISSUE THREAD

**Issue by TessaBakker** [drush-ops/drush-launcher#77]
**Current**

1. `drush use @example.dev && drush status` doesn't show any variables from the configured alias.
2. `./vendor/bin/drush use @example.dev && ./vendor/bin/drush status` shows all the variables from the used alias.

**Expected**
Drush launcher shows exactly the same output as ./vender/bin/drush when a `site:set`/`use` is used.

**Setup**
* Drush Launcher (0.6, global) 
* Drush (10.1.1, project vendor)
* Drupal (8.8.1, composer project)

**Alias file** `[project root]/drush/sites/example.site.yml`:
```yml
dev:
  uri: https://example.drupal.local:9443
  root: /var/www/app/web
  docker:
    service: app
    exec:
      options: -u1000
  paths:
    drush-script: '/var/www/app/vendor/bin/drush'
```
